# Generated by Django 5.1.6 on 2025-03-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('sprint', models.IntegerField(choices=[(1, 'Sprint 1'), (2, 'Sprint 2'), (3, 'Sprint 3'), (4, 'Sprint 4'), (5, 'Sprint 5'), (6, 'Sprint 6'), (7, 'Sprint 7'), (8, 'Sprint 8'), (9, 'Sprint 9'), (10, 'Sprint 10')])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('linear', 'Escala Linear'), ('multiple', 'Múltipla Escolha')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_easyretro.form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_easyretro.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_easyretro.question')),
            ],
        ),
    ]
